<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

<Version>2.2.1</Version>
<AssemblyVersion>2.2.1.0</AssemblyVersion>
<FileVersion>2.2.1.0</FileVersion>
<InformationalVersion>2.2.1</InformationalVersion>

    <!-- Informations -->
    <Company>theJim</Company>
    <Product>RetroBat GameList Comparator</Product>
    <Authors>theJim</Authors>
    <Copyright>© 2026 theJim</Copyright>
    <Description>Compare RetroBat ROM folders with gamelist.xml while supporting Hidden and MultiDisk games.</Description>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exports\**" />
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Exports\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Exports\**" />
    <None Remove="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\Extensions.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\Extensions.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\UI.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UI.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>